apiVersion: v2
name: test-2
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: "1.16.0"
dependencies:
  - name: rabbitmq
    # https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq
    version: "12.2.3"
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
